[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.5.1" }
wally = { github = "UpliftGames/wally", version = "0.3.2" }
wally-package-types = { github = "johnnymorganz/wally-package-types", version = "1.5.1" }
selene = { github = "Kampfkarren/selene", version = "0.28.0" }
stylua = { github = "johnnymorganz/stylua", version = "2.1.0" }
luau-lsp = { github = "johnnymorganz/luau-lsp", version = "1.52.1" }